// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package models

type CreateInvInput struct {
	Name    string `json:"name"`
	Address string `json:"address"`
}

type CreateItemInput struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	Status      string `json:"status"`
}

type CreateUserInput struct {
	FirstName     string  `json:"firstName"`
	LastName      string  `json:"lastName"`
	Username      string  `json:"username"`
	Password      string  `json:"password"`
	RolesID       string  `json:"rolesId"`
	InventoriesID *string `json:"inventoriesId"`
}

type LoginInput struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type UpdateInvInput struct {
	ID      string  `json:"id"`
	Name    *string `json:"name"`
	Address *string `json:"address"`
}

type UpdateItemInput struct {
	ID            string  `json:"id"`
	Name          *string `json:"name"`
	Description   *string `json:"description"`
	Status        *string `json:"status"`
	InventoriesID *string `json:"inventoriesId"`
}

type UpdateUserInput struct {
	ID            string  `json:"id"`
	FirstName     *string `json:"firstName"`
	LastName      *string `json:"lastName"`
	Username      *string `json:"username"`
	Password      *string `json:"password"`
	RolesID       *string `json:"rolesId"`
	InventoriesID *string `json:"inventoriesId"`
}
